// Auto-generated data matching Yacine TV style functionality
import { Category, Channel, Match } from "./types";

export const CATEGORIES: Category[] = [
  {
    id: "sports",
    name: "Live Sports",
    color: "bg-red-600",
  },
  {
    id: "movies",
    name: "Movies & Cinema",
    color: "bg-purple-600",
  },
  {
    id: "entertainment",
    name: "Arabic & Entertainment",
    color: "bg-blue-600",
  },
  {
    id: "kids",
    name: "Kids",
    color: "bg-yellow-500",
  },
  {
    id: "news",
    name: "News",
    color: "bg-zinc-600",
  },
];

export const CHANNELS: Channel[] = [
  {
    id: "ch-req-hvt9",
    name: "beIN SPORTS HD",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=beIN%20SPORTS%20HD&background=5b21b6&color=fff&size=128",
    streamUrl:
      "https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8",
  },
  {
    id: "ch-req-ydnb",
    name: "beIN SPORTS NEWS HD",
    categoryId: "news",
    logo: "https://ui-avatars.com/api/?name=beIN%20SPORTS%20NEWS%20HD&background=5b21b6&color=fff&size=128",
    streamUrl: "https://bein-beinxtrasports-firetv.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-req-ug8y",
    name: "beIN SPORTS 1",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=beIN%20SPORTS%201&background=5b21b6&color=fff&size=128",
    streamUrl: "https://bein-esp-xumo.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-req-0mrj",
    name: "beIN SPORTS 2",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=beIN%20SPORTS%202&background=5b21b6&color=fff&size=128",
    streamUrl: "https://static.france24.com/live/F24_EN_HI_HLS/live_web.m3u8",
  },
  {
    id: "ch-req-mtht",
    name: "beIN SPORTS 3",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=beIN%20SPORTS%203&background=5b21b6&color=fff&size=128",
    streamUrl: "https://live-hls-web-aja.getaj.net/AJA/index.m3u8",
  },
  {
    id: "ch-req-xhtv",
    name: "beIN SPORTS 4",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=beIN%20SPORTS%204&background=5b21b6&color=fff&size=128",
    streamUrl:
      "https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8",
  },
  {
    id: "ch-req-ial7",
    name: "beIN SPORTS 5",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=beIN%20SPORTS%205&background=5b21b6&color=fff&size=128",
    streamUrl: "https://bein-beinxtrasports-firetv.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-req-6b9b",
    name: "beIN SPORTS 6",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=beIN%20SPORTS%206&background=5b21b6&color=fff&size=128",
    streamUrl: "https://bein-esp-xumo.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-req-1lyd",
    name: "beIN SPORTS 1 EN",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=beIN%20SPORTS%201%20EN&background=5b21b6&color=fff&size=128",
    streamUrl: "https://static.france24.com/live/F24_EN_HI_HLS/live_web.m3u8",
  },
  {
    id: "ch-req-qv80",
    name: "beIN SPORTS 2 EN",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=beIN%20SPORTS%202%20EN&background=5b21b6&color=fff&size=128",
    streamUrl: "https://live-hls-web-aja.getaj.net/AJA/index.m3u8",
  },
  {
    id: "ch-req-1zfh",
    name: "beIN SPORTS 1 FR",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=beIN%20SPORTS%201%20FR&background=5b21b6&color=fff&size=128",
    streamUrl:
      "https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8",
  },
  {
    id: "ch-req-cw8k",
    name: "beIN SPORTS 2 FR",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=beIN%20SPORTS%202%20FR&background=5b21b6&color=fff&size=128",
    streamUrl: "https://bein-beinxtrasports-firetv.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-req-ssim",
    name: "beIN SPORTS NBA",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=beIN%20SPORTS%20NBA&background=5b21b6&color=fff&size=128",
    streamUrl: "https://bein-esp-xumo.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-req-lspa",
    name: "beIN SPORTS MAX 1",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=beIN%20SPORTS%20MAX%201&background=5b21b6&color=fff&size=128",
    streamUrl: "https://static.france24.com/live/F24_EN_HI_HLS/live_web.m3u8",
  },
  {
    id: "ch-req-5bdx",
    name: "beIN SPORTS MAX 2",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=beIN%20SPORTS%20MAX%202&background=5b21b6&color=fff&size=128",
    streamUrl: "https://live-hls-web-aja.getaj.net/AJA/index.m3u8",
  },
  {
    id: "ch-req-deru",
    name: "beIN SPORTS MAX 3",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=beIN%20SPORTS%20MAX%203&background=5b21b6&color=fff&size=128",
    streamUrl:
      "https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8",
  },
  {
    id: "ch-req-59sx",
    name: "beIN SPORTS MAX 4",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=beIN%20SPORTS%20MAX%204&background=5b21b6&color=fff&size=128",
    streamUrl: "https://bein-beinxtrasports-firetv.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-req-fcxr",
    name: "beIN SPORTS MAX 5",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=beIN%20SPORTS%20MAX%205&background=5b21b6&color=fff&size=128",
    streamUrl: "https://bein-esp-xumo.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-req-vdjd",
    name: "beIN SPORTS MAX 6",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=beIN%20SPORTS%20MAX%206&background=5b21b6&color=fff&size=128",
    streamUrl: "https://static.france24.com/live/F24_EN_HI_HLS/live_web.m3u8",
  },
  {
    id: "ch-req-xy61",
    name: "beIN BOX OFFICE 1",
    categoryId: "movies",
    logo: "https://ui-avatars.com/api/?name=beIN%20BOX%20OFFICE%201&background=5b21b6&color=fff&size=128",
    streamUrl: "https://live-hls-web-aja.getaj.net/AJA/index.m3u8",
  },
  {
    id: "ch-req-jw9x",
    name: "beIN BOX OFFICE 2",
    categoryId: "movies",
    logo: "https://ui-avatars.com/api/?name=beIN%20BOX%20OFFICE%202&background=5b21b6&color=fff&size=128",
    streamUrl:
      "https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8",
  },
  {
    id: "ch-bein-beINSPORTSXTRA.us-5r8w",
    name: "beIN SPORTS XTRA",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=beIN%20SPORTS%20XTRA&background=2563eb&color=fff&size=128",
    streamUrl: "https://bein-beinxtrasports-firetv.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-bein-beINSPORTSXTRA.us-da7v",
    name: "beIN SPORTS XTRA",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=beIN%20SPORTS%20XTRA&background=2563eb&color=fff&size=128",
    streamUrl: "https://bein-esp-xumo.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-bein-beINSPORTSXTRA.us-bhbz",
    name: "beIN SPORTS XTRA",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=beIN%20SPORTS%20XTRA&background=2563eb&color=fff&size=128",
    streamUrl: "https://static.france24.com/live/F24_EN_HI_HLS/live_web.m3u8",
  },
  {
    id: "ch-bein-beINSPORTSXTRA.us-4ljs",
    name: "beIN SPORTS XTRA",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=beIN%20SPORTS%20XTRA&background=2563eb&color=fff&size=128",
    streamUrl: "https://live-hls-web-aja.getaj.net/AJA/index.m3u8",
  },
  {
    id: "ch-bein-beINSPORTSXTRA.us-65g4",
    name: "beIN SPORTS XTRA",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=beIN%20SPORTS%20XTRA&background=2563eb&color=fff&size=128",
    streamUrl:
      "https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8",
  },
  {
    id: "ch-bein-beINSPORTSXTRA.us-qhx7",
    name: "beIN SPORTS XTRA",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=beIN%20SPORTS%20XTRA&background=2563eb&color=fff&size=128",
    streamUrl: "https://bein-beinxtrasports-firetv.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-bein-beINSPORTSXTRAenEspanol.us-tj8g",
    name: "beIN SPORTS XTRA en Espanol",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=beIN%20SPORTS%20XTRA%20en%20Espanol&background=2563eb&color=fff&size=128",
    streamUrl: "https://bein-esp-xumo.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-bein-beINSPORTSXTRAenEspanol.us-00s6",
    name: "beIN SPORTS XTRA en Espanol",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=beIN%20SPORTS%20XTRA%20en%20Espanol&background=2563eb&color=fff&size=128",
    streamUrl: "https://static.france24.com/live/F24_EN_HI_HLS/live_web.m3u8",
  },
  {
    id: "ch-bein-beINSPORTSXTRAenEspanol.us-skm4",
    name: "beIN SPORTS XTRA en Espanol",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=beIN%20SPORTS%20XTRA%20en%20Espanol&background=2563eb&color=fff&size=128",
    streamUrl: "https://live-hls-web-aja.getaj.net/AJA/index.m3u8",
  },
  {
    id: "ch-bein-beINSPORTSXTRAenEspanol.us-84x7",
    name: "beIN SPORTS XTRA en Espanol",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=beIN%20SPORTS%20XTRA%20en%20Espanol&background=2563eb&color=fff&size=128",
    streamUrl:
      "https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8",
  },
  {
    id: "ch-30AGolfKingdom.us",
    name: "30A Golf Kingdom",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=30A%20Golf%20Kingdom&background=2563eb&color=fff&size=128",
    streamUrl: "https://bein-beinxtrasports-firetv.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-ACCDigitalNetwork.us",
    name: "ACC Digital Network",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=ACC%20Digital%20Network&background=2563eb&color=fff&size=128",
    streamUrl: "https://bein-esp-xumo.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-ACISportTV.it",
    name: "ACI Sport TV",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=ACI%20Sport%20TV&background=2563eb&color=fff&size=128",
    streamUrl: "https://static.france24.com/live/F24_EN_HI_HLS/live_web.m3u8",
  },
  {
    id: "ch-AlkassFive.qa",
    name: "Alkass Five",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=Alkass%20Five&background=2563eb&color=fff&size=128",
    streamUrl: "https://live-hls-web-aja.getaj.net/AJA/index.m3u8",
  },
  {
    id: "ch-AlkassFour.qa",
    name: "Alkass Four",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=Alkass%20Four&background=2563eb&color=fff&size=128",
    streamUrl:
      "https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8",
  },
  {
    id: "ch-AlkassOne.qa",
    name: "Alkass One",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=Alkass%20One&background=2563eb&color=fff&size=128",
    streamUrl: "https://bein-beinxtrasports-firetv.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-AlkassSHOOF2.qa",
    name: "Alkass SHOOF 2",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=Alkass%20SHOOF%202&background=2563eb&color=fff&size=128",
    streamUrl: "https://bein-esp-xumo.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-AlkassSHOOF.qa",
    name: "Alkass SHOOF",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=Alkass%20SHOOF&background=2563eb&color=fff&size=128",
    streamUrl: "https://static.france24.com/live/F24_EN_HI_HLS/live_web.m3u8",
  },
  {
    id: "ch-AlkassSix.qa",
    name: "Alkass Six",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=Alkass%20Six&background=2563eb&color=fff&size=128",
    streamUrl: "https://live-hls-web-aja.getaj.net/AJA/index.m3u8",
  },
  {
    id: "ch-AlkassThree.qa",
    name: "Alkass Three",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=Alkass%20Three&background=2563eb&color=fff&size=128",
    streamUrl:
      "https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8",
  },
  {
    id: "ch-AlkassTwo.qa",
    name: "Alkass Two",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=Alkass%20Two&background=2563eb&color=fff&size=128",
    streamUrl: "https://bein-beinxtrasports-firetv.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-AntenaSport.ro",
    name: "AntenaSport",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=AntenaSport&background=2563eb&color=fff&size=128",
    streamUrl: "https://bein-esp-xumo.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-AS3SportTV.ve",
    name: "AS3 Sport TV",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=AS3%20Sport%20TV&background=2563eb&color=fff&size=128",
    streamUrl: "https://static.france24.com/live/F24_EN_HI_HLS/live_web.m3u8",
  },
  {
    id: "ch-AstrahanRuSport.ru",
    name: "Astrahan.Ru Sport",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=Astrahan.Ru%20Sport&background=2563eb&color=fff&size=128",
    streamUrl: "https://live-hls-web-aja.getaj.net/AJA/index.m3u8",
  },
  {
    id: "ch-ATGLive.se",
    name: "ATG Live",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=ATG%20Live&background=2563eb&color=fff&size=128",
    streamUrl:
      "https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8",
  },
  {
    id: "ch-BahrainSports1.bh",
    name: "Bahrain Sports 1",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=Bahrain%20Sports%201&background=2563eb&color=fff&size=128",
    streamUrl: "https://bein-beinxtrasports-firetv.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-BahrainSports2.bh",
    name: "Bahrain Sports 2",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=Bahrain%20Sports%202&background=2563eb&color=fff&size=128",
    streamUrl: "https://bein-esp-xumo.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-beINSPORTSXTRA.us",
    name: "beIN SPORTS XTRA",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=beIN%20SPORTS%20XTRA&background=2563eb&color=fff&size=128",
    streamUrl: "https://static.france24.com/live/F24_EN_HI_HLS/live_web.m3u8",
  },
  {
    id: "ch-BEKSports.us",
    name: "BEK Sports",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=BEK%20Sports&background=2563eb&color=fff&size=128",
    streamUrl: "https://live-hls-web-aja.getaj.net/AJA/index.m3u8",
  },
  {
    id: "ch-Belarus5.by",
    name: "Belarus-5",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=Belarus-5&background=2563eb&color=fff&size=128",
    streamUrl:
      "https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8",
  },
  {
    id: "ch-BellatorMMA.us",
    name: "Bellator MMA",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=Bellator%20MMA&background=2563eb&color=fff&size=128",
    streamUrl: "https://bein-beinxtrasports-firetv.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-BoksTV.ru",
    name: "Boks TV",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=Boks%20TV&background=2563eb&color=fff&size=128",
    streamUrl: "http://31.148.48.15/Boks_TV/index.m3u8",
  },
  {
    id: "ch-CazeTV.br",
    name: "CazeTV",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=CazeTV&background=2563eb&color=fff&size=128",
    streamUrl: "https://bein-esp-xumo.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-CCTV5.cn",
    name: "CCTV-5",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=CCTV-5&background=2563eb&color=fff&size=128",
    streamUrl: "http://74.91.26.218:82/live/cctv5hd.m3u8",
  },
  {
    id: "ch-CCTV5Plus.cn",
    name: "CCTV-5+",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=CCTV-5%2B&background=2563eb&color=fff&size=128",
    streamUrl: "http://192.151.150.154/live/cctv5p.m3u8",
  },
  {
    id: "ch-CCTV16.cn",
    name: "CCTV-16",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=CCTV-16&background=2563eb&color=fff&size=128",
    streamUrl: "http://74.91.26.218:82/live/cctv16hd.m3u8",
  },
  {
    id: "ch-CCTVBilliards.cn",
    name: "CCTV-Billiards",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=CCTV-Billiards&background=2563eb&color=fff&size=128",
    streamUrl: "http://38.75.136.137:98/gslb/dsdqpub/ystq.m3u8?auth=testpub",
  },
  {
    id: "ch-CCTVGolfTennis.cn",
    name: "CCTV-Golf & Tennis",
    categoryId: "sports",
    logo: "https://ui-avatars.com/api/?name=CCTV-Golf%20%26%20Tennis&background=2563eb&color=fff&size=128",
    streamUrl: "http://38.75.136.137:98/gslb/dsdqpub/gefwq.m3u8?auth=testpub",
  },
  {
    id: "ch-2GB.au",
    name: "2GB",
    categoryId: "news",
    logo: "https://ui-avatars.com/api/?name=2GB&background=2563eb&color=fff&size=128",
    streamUrl: "https://static.france24.com/live/F24_EN_HI_HLS/live_web.m3u8",
  },
  {
    id: "ch-3AW.au",
    name: "3AW",
    categoryId: "news",
    logo: "https://ui-avatars.com/api/?name=3AW&background=2563eb&color=fff&size=128",
    streamUrl: "https://live-hls-web-aja.getaj.net/AJA/index.m3u8",
  },
  {
    id: "ch-3CatInfo.es",
    name: "3CatInfo",
    categoryId: "news",
    logo: "https://ui-avatars.com/api/?name=3CatInfo&background=2563eb&color=fff&size=128",
    streamUrl:
      "https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8",
  },
  {
    id: "ch-4TVNews.in",
    name: "4TV News",
    categoryId: "news",
    logo: "https://ui-avatars.com/api/?name=4TV%20News&background=2563eb&color=fff&size=128",
    streamUrl: "https://bein-beinxtrasports-firetv.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-6PR.au",
    name: "6PR",
    categoryId: "news",
    logo: "https://ui-avatars.com/api/?name=6PR&background=2563eb&color=fff&size=128",
    streamUrl: "https://bein-esp-xumo.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-6TVTelugu.in",
    name: "6 TV Telugu",
    categoryId: "news",
    logo: "https://ui-avatars.com/api/?name=6%20TV%20Telugu&background=2563eb&color=fff&size=128",
    streamUrl: "https://static.france24.com/live/F24_EN_HI_HLS/live_web.m3u8",
  },
  {
    id: "ch-10TV.in",
    name: "10 TV",
    categoryId: "news",
    logo: "https://ui-avatars.com/api/?name=10%20TV&background=2563eb&color=fff&size=128",
    streamUrl: "https://live-hls-web-aja.getaj.net/AJA/index.m3u8",
  },
  {
    id: "ch-13SiamThai.th",
    name: "13 Siam Thai",
    categoryId: "news",
    logo: "https://ui-avatars.com/api/?name=13%20Siam%20Thai&background=2563eb&color=fff&size=128",
    streamUrl:
      "https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8",
  },
  {
    id: "ch-22ScopeNews.in",
    name: "22Scope News",
    categoryId: "news",
    logo: "https://ui-avatars.com/api/?name=22Scope%20News&background=2563eb&color=fff&size=128",
    streamUrl: "https://bein-beinxtrasports-firetv.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-24HorasCanarias.es",
    name: "24 Horas Canarias",
    categoryId: "news",
    logo: "https://ui-avatars.com/api/?name=24%20Horas%20Canarias&background=2563eb&color=fff&size=128",
    streamUrl: "https://bein-esp-xumo.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-24HorasCatalunya.es",
    name: "24 Horas Catalunya",
    categoryId: "news",
    logo: "https://ui-avatars.com/api/?name=24%20Horas%20Catalunya&background=2563eb&color=fff&size=128",
    streamUrl: "https://static.france24.com/live/F24_EN_HI_HLS/live_web.m3u8",
  },
  {
    id: "ch-24News.in",
    name: "24 News",
    categoryId: "news",
    logo: "https://ui-avatars.com/api/?name=24%20News&background=2563eb&color=fff&size=128",
    streamUrl: "https://live-hls-web-aja.getaj.net/AJA/index.m3u8",
  },
  {
    id: "ch-24.sk",
    name: ":24",
    categoryId: "news",
    logo: "https://ui-avatars.com/api/?name=%3A24&background=2563eb&color=fff&size=128",
    streamUrl: "http://88.212.15.27/live/test_trojka_25p/playlist.m3u8",
  },
  {
    id: "ch-24HourFreeMovies.us",
    name: "24 Hour Free Movies",
    categoryId: "movies",
    logo: "https://ui-avatars.com/api/?name=24%20Hour%20Free%20Movies&background=2563eb&color=fff&size=128",
    streamUrl:
      "https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8",
  },
  {
    id: "ch-30ATVClassicMovies.us",
    name: "30A TV Classic Movies",
    categoryId: "movies",
    logo: "https://ui-avatars.com/api/?name=30A%20TV%20Classic%20Movies&background=2563eb&color=fff&size=128",
    streamUrl: "https://bein-beinxtrasports-firetv.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-50CentAction.us",
    name: "50 Cent Action",
    categoryId: "movies",
    logo: "https://ui-avatars.com/api/?name=50%20Cent%20Action&background=2563eb&color=fff&size=128",
    streamUrl: "https://bein-esp-xumo.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-70sCinema.us",
    name: "70s Cinema",
    categoryId: "movies",
    logo: "https://ui-avatars.com/api/?name=70s%20Cinema&background=2563eb&color=fff&size=128",
    streamUrl: "https://static.france24.com/live/F24_EN_HI_HLS/live_web.m3u8",
  },
  {
    id: "ch-80sRewind.us",
    name: "80s Rewind",
    categoryId: "movies",
    logo: "https://ui-avatars.com/api/?name=80s%20Rewind&background=2563eb&color=fff&size=128",
    streamUrl: "https://live-hls-web-aja.getaj.net/AJA/index.m3u8",
  },
  {
    id: "ch-90sThrowback.us",
    name: "90s Throwback",
    categoryId: "movies",
    logo: "https://ui-avatars.com/api/?name=90s%20Throwback&background=2563eb&color=fff&size=128",
    streamUrl:
      "https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8",
  },
  {
    id: "ch-312Kino.kg",
    name: "312 Kino",
    categoryId: "movies",
    logo: "https://ui-avatars.com/api/?name=312%20Kino&background=2563eb&color=fff&size=128",
    streamUrl: "http://176.126.166.43:1935/live/312kino/playlist.m3u8",
  },
  {
    id: "ch-Action24.gr",
    name: "Action 24",
    categoryId: "movies",
    logo: "https://ui-avatars.com/api/?name=Action%2024&background=2563eb&color=fff&size=128",
    streamUrl:
      "http://actionlive.siliconweb.com/actionabr/actiontv/playlist.m3u8",
  },
  {
    id: "ch-AdrenalinaPuraTV.us",
    name: "Adrenalina Pura TV",
    categoryId: "movies",
    logo: "https://ui-avatars.com/api/?name=Adrenalina%20Pura%20TV&background=2563eb&color=fff&size=128",
    streamUrl: "https://bein-beinxtrasports-firetv.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-Aflam.sa",
    name: "Aflam",
    categoryId: "movies",
    logo: "https://ui-avatars.com/api/?name=Aflam&background=2563eb&color=fff&size=128",
    streamUrl: "https://bein-esp-xumo.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-AfraFilm.ir",
    name: "Afra Film",
    categoryId: "movies",
    logo: "https://ui-avatars.com/api/?name=Afra%20Film&background=2563eb&color=fff&size=128",
    streamUrl: "https://static.france24.com/live/F24_EN_HI_HLS/live_web.m3u8",
  },
  {
    id: "ch-AfriwoodBlockbuster.za",
    name: "Afriwood Blockbuster",
    categoryId: "movies",
    logo: "https://ui-avatars.com/api/?name=Afriwood%20Blockbuster&background=2563eb&color=fff&size=128",
    streamUrl: "https://live-hls-web-aja.getaj.net/AJA/index.m3u8",
  },
  {
    id: "ch-AlankarTV.in",
    name: "Alankar TV",
    categoryId: "movies",
    logo: "https://ui-avatars.com/api/?name=Alankar%20TV&background=2563eb&color=fff&size=128",
    streamUrl:
      "https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8",
  },
  {
    id: "ch-AmediaHit.ru",
    name: "Amedia Hit",
    categoryId: "movies",
    logo: "https://ui-avatars.com/api/?name=Amedia%20Hit&background=2563eb&color=fff&size=128",
    streamUrl: "http://31.148.48.15/Amedia_HIT_HD/index.m3u8",
  },
  {
    id: "ch-AmericanHorrors.us",
    name: "American Horrors",
    categoryId: "movies",
    logo: "https://ui-avatars.com/api/?name=American%20Horrors&background=2563eb&color=fff&size=128",
    streamUrl: "http://107.167.7.162:8081/playlist/amhor/playlist.m3u8",
  },
  {
    id: "ch-3ABNKids.us",
    name: "3ABN Kids",
    categoryId: "kids",
    logo: "https://ui-avatars.com/api/?name=3ABN%20Kids&background=2563eb&color=fff&size=128",
    streamUrl: "https://bein-beinxtrasports-firetv.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-4FunKids.pl",
    name: "4 Fun Kids",
    categoryId: "kids",
    logo: "https://ui-avatars.com/api/?name=4%20Fun%20Kids&background=2563eb&color=fff&size=128",
    streamUrl: "https://bein-esp-xumo.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-13Kids.cl",
    name: "13 Kids",
    categoryId: "kids",
    logo: "https://ui-avatars.com/api/?name=13%20Kids&background=2563eb&color=fff&size=128",
    streamUrl: "https://static.france24.com/live/F24_EN_HI_HLS/live_web.m3u8",
  },
  {
    id: "ch-ABCKids.au",
    name: "ABC Kids",
    categoryId: "kids",
    logo: "https://ui-avatars.com/api/?name=ABC%20Kids&background=2563eb&color=fff&size=128",
    streamUrl: "https://live-hls-web-aja.getaj.net/AJA/index.m3u8",
  },
  {
    id: "ch-ADOTV.bj",
    name: "ADO TV",
    categoryId: "kids",
    logo: "https://ui-avatars.com/api/?name=ADO%20TV&background=2563eb&color=fff&size=128",
    streamUrl:
      "https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8",
  },
  {
    id: "ch-AfarinBaxcha.iq",
    name: "Afarin Baxcha",
    categoryId: "kids",
    logo: "https://ui-avatars.com/api/?name=Afarin%20Baxcha&background=2563eb&color=fff&size=128",
    streamUrl: "https://bein-beinxtrasports-firetv.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-AghapyKids.us",
    name: "Aghapy Kids",
    categoryId: "kids",
    logo: "https://ui-avatars.com/api/?name=Aghapy%20Kids&background=2563eb&color=fff&size=128",
    streamUrl: "https://bein-esp-xumo.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-AmouYazidTV.dz",
    name: "Amou Yazid TV",
    categoryId: "kids",
    logo: "https://ui-avatars.com/api/?name=Amou%20Yazid%20TV&background=2563eb&color=fff&size=128",
    streamUrl: "http://mkstream.servehttp.com:1940/AmouYazid/ay1/playlist.m3u8",
  },
  {
    id: "ch-Ananda.id",
    name: "Ananda",
    categoryId: "kids",
    logo: "https://ui-avatars.com/api/?name=Ananda&background=2563eb&color=fff&size=128",
    streamUrl: "https://static.france24.com/live/F24_EN_HI_HLS/live_web.m3u8",
  },
  {
    id: "ch-Ani.ru",
    name: "Ani",
    categoryId: "kids",
    logo: "https://ui-avatars.com/api/?name=Ani&background=2563eb&color=fff&size=128",
    streamUrl: "http://31.148.48.15/Ani/index.m3u8",
  },
  {
    id: "ch-ARBGunes.az",
    name: "ARB Gunes",
    categoryId: "kids",
    logo: "https://ui-avatars.com/api/?name=ARB%20Gunes&background=2563eb&color=fff&size=128",
    streamUrl: "https://live-hls-web-aja.getaj.net/AJA/index.m3u8",
  },
  {
    id: "ch-AtfalMawahebTV.sa",
    name: "Atfal & Mawaheb TV",
    categoryId: "kids",
    logo: "https://ui-avatars.com/api/?name=Atfal%20%26%20Mawaheb%20TV&background=2563eb&color=fff&size=128",
    streamUrl:
      "https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8",
  },
  {
    id: "ch-Avatar.us",
    name: "Avatar",
    categoryId: "kids",
    logo: "https://ui-avatars.com/api/?name=Avatar&background=2563eb&color=fff&size=128",
    streamUrl: "https://bein-beinxtrasports-firetv.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-BabyFirst.us",
    name: "BabyFirst",
    categoryId: "kids",
    logo: "https://ui-avatars.com/api/?name=BabyFirst&background=2563eb&color=fff&size=128",
    streamUrl: "https://bein-esp-xumo.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-BabySharkTV.us",
    name: "Baby Shark TV",
    categoryId: "kids",
    logo: "https://ui-avatars.com/api/?name=Baby%20Shark%20TV&background=2563eb&color=fff&size=128",
    streamUrl: "https://static.france24.com/live/F24_EN_HI_HLS/live_web.m3u8",
  },
  {
    id: "ch-BabyTV.uk",
    name: "BabyTV",
    categoryId: "kids",
    logo: "https://ui-avatars.com/api/?name=BabyTV&background=2563eb&color=fff&size=128",
    streamUrl: "https://live-hls-web-aja.getaj.net/AJA/index.m3u8",
  },
  {
    id: "ch-Balapan.kz",
    name: "Balapan",
    categoryId: "kids",
    logo: "https://ui-avatars.com/api/?name=Balapan&background=2563eb&color=fff&size=128",
    streamUrl:
      "https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8",
  },
  {
    id: "ch-1KZNTV.za",
    name: "1KZN TV",
    categoryId: "entertainment",
    logo: "https://ui-avatars.com/api/?name=1KZN%20TV&background=2563eb&color=fff&size=128",
    streamUrl: "https://bein-beinxtrasports-firetv.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-2x2.ru",
    name: "2x2",
    categoryId: "entertainment",
    logo: "https://ui-avatars.com/api/?name=2x2&background=2563eb&color=fff&size=128",
    streamUrl: "https://bein-esp-xumo.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-4UTV.tr",
    name: "4U TV",
    categoryId: "entertainment",
    logo: "https://ui-avatars.com/api/?name=4U%20TV&background=2563eb&color=fff&size=128",
    streamUrl: "https://static.france24.com/live/F24_EN_HI_HLS/live_web.m3u8",
  },
  {
    id: "ch-5AABTV.ca",
    name: "5AAB TV",
    categoryId: "entertainment",
    logo: "https://ui-avatars.com/api/?name=5AAB%20TV&background=2563eb&color=fff&size=128",
    streamUrl: "http://158.69.124.9:1935/5aabtv/5aabtv/playlist.m3u8",
  },
  {
    id: "ch-13E.cl",
    name: "13E",
    categoryId: "entertainment",
    logo: "https://ui-avatars.com/api/?name=13E&background=2563eb&color=fff&size=128",
    streamUrl: "https://live-hls-web-aja.getaj.net/AJA/index.m3u8",
  },
  {
    id: "ch-13Realities.cl",
    name: "13 Realities",
    categoryId: "entertainment",
    logo: "https://ui-avatars.com/api/?name=13%20Realities&background=2563eb&color=fff&size=128",
    streamUrl:
      "https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8",
  },
  {
    id: "ch-30AGeorgiaHollywoodReview.us",
    name: "30A Georgia Hollywood Review",
    categoryId: "entertainment",
    logo: "https://ui-avatars.com/api/?name=30A%20Georgia%20Hollywood%20Review&background=2563eb&color=fff&size=128",
    streamUrl: "https://bein-beinxtrasports-firetv.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-30ASidewalks.us",
    name: "30A Sidewalks",
    categoryId: "entertainment",
    logo: "https://ui-avatars.com/api/?name=30A%20Sidewalks&background=2563eb&color=fff&size=128",
    streamUrl: "https://bein-esp-xumo.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-30ATelevisionChannel.us",
    name: "30A Television Channel",
    categoryId: "entertainment",
    logo: "https://ui-avatars.com/api/?name=30A%20Television%20Channel&background=2563eb&color=fff&size=128",
    streamUrl: "https://static.france24.com/live/F24_EN_HI_HLS/live_web.m3u8",
  },
  {
    id: "ch-247BoxTV.ir",
    name: "247 Box TV",
    categoryId: "entertainment",
    logo: "https://ui-avatars.com/api/?name=247%20Box%20TV&background=2563eb&color=fff&size=128",
    streamUrl: "https://live-hls-web-aja.getaj.net/AJA/index.m3u8",
  },
  {
    id: "ch-312TV.kg",
    name: "312 TV",
    categoryId: "entertainment",
    logo: "https://ui-avatars.com/api/?name=312%20TV&background=2563eb&color=fff&size=128",
    streamUrl: "http://176.126.166.43:1935/live/312musik/playlist.m3u8",
  },
  {
    id: "ch-AajEntertainment.pk",
    name: "Aaj Entertainment",
    categoryId: "entertainment",
    logo: "https://ui-avatars.com/api/?name=Aaj%20Entertainment&background=2563eb&color=fff&size=128",
    streamUrl:
      "https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8",
  },
  {
    id: "ch-AakaashAath.in",
    name: "Aakaash Aath",
    categoryId: "entertainment",
    logo: "https://ui-avatars.com/api/?name=Aakaash%20Aath&background=2563eb&color=fff&size=128",
    streamUrl: "https://bein-beinxtrasports-firetv.amagi.tv/playlist.m3u8",
  },
  {
    id: "ch-AamarBangla.in",
    name: "Aamar Bangla",
    categoryId: "entertainment",
    logo: "https://ui-avatars.com/api/?name=Aamar%20Bangla&background=2563eb&color=fff&size=128",
    streamUrl: "https://bein-esp-xumo.amagi.tv/playlist.m3u8",
  },
];

import { addHours, subMinutes, subHours } from "date-fns";
const now = new Date();
export const MATCHES: Match[] = [
  {
    id: "m-1",
    league: "Premier League",
    homeTeam: {
      id: "t-ars",
      name: "Arsenal",
      logo: "https://ui-avatars.com/api/?name=AR&background=ef4444&color=fff&size=64",
      score: 2,
    },
    awayTeam: {
      id: "t-mci",
      name: "Man City",
      logo: "https://ui-avatars.com/api/?name=MC&background=60a5fa&color=fff&size=64",
      score: 1,
    },
    startTime: subMinutes(now, 45).toISOString(),
    status: "LIVE",
    channelId: "ch-req-hvt9",
    commentator: "Issam Chaouali",
  },
];
